# Generated by Django 2.0.5 on 2018-12-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfomodel',
            name='reg_num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
