# Generated by Django 2.0.5 on 2019-01-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_doctorinfomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfomodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='DoctorInfoModel',
        ),
    ]
