# Generated by Django 2.0.5 on 2019-01-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='appointed',
            field=models.CharField(default='no', max_length=4),
        ),
    ]
